version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Linting the code
      - npm run lint
      - echo Starting unit tests at `date`
      - npm test
      - echo Unit tests execution complete at `date`
  post_build:
    commands:
      - echo Remove existing node_modules to clear dev dependencies
      - rm -r node_modules
      - echo Install runtime dependencies
      - npm install --production
artifacts:
  type: zip
  files:
    - README.md
    - package.json
    - lib/*
    - server.js
    - appspec.yml
    - .ebextensions/*
    - node_modules/**/*